### ISSUE TITLE
Getting a build failure with 1.6.1

### ISSUE THREAD

**Issue by jubalh** [gkarsay/parlatype#63]
Trying to build parlatype 1.6.1 tarball in a build environment I get the following:

```
[    2s] + /usr/bin/gzip -dc /home/abuild/rpmbuild/SOURCES/parlatype-1.6.1.tar.gz
[    2s] + /usr/bin/tar -xof -
[    2s] + STATUS=0
[    2s] + '[' 0 -ne 0 ']'
[    2s] + cd parlatype-1.6.1
[    2s] + /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
[    2s] + exit 0
[    2s] Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.GOOBWZ
[    2s] + umask 022
[    2s] + cd /home/abuild/rpmbuild/BUILD
[    2s] + /usr/bin/rm -rf /home/abuild/rpmbuild/BUILDROOT/parlatype-1.6.1-0.x86_64
[    2s] ++ dirname /home/abuild/rpmbuild/BUILDROOT/parlatype-1.6.1-0.x86_64
[    2s] + /usr/bin/mkdir -p /home/abuild/rpmbuild/BUILDROOT
[    2s] + /usr/bin/mkdir /home/abuild/rpmbuild/BUILDROOT/parlatype-1.6.1-0.x86_64
[    2s] + cd parlatype-1.6.1
[    2s] + export LANG=C.UTF-8
[    2s] + LANG=C.UTF-8
[    2s] + export 'CFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + CFLAGS='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + export 'CXXFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + CXXFLAGS='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + export 'FFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + FFLAGS='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + export 'FCFLAGS=-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + FCFLAGS='-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    2s] + /usr/bin/meson --buildtype=plain --prefix=/usr --libdir=/usr/lib64 --libexecdir=/usr/lib --bindir=/usr/bin --sbindir=/usr/sbin --includedir=/usr/include --datadir=/usr/share --mandir=/usr/share/man --infodir=/usr/share/info --localedir=/usr/share/locale --sysconfdir=/etc --localstatedir=/var --sharedstatedir=/var/lib --wrap-mode=nodownload --auto-features=enabled . build -Dasr=false
[    3s] The Meson build system
[    3s] Version: 0.51.0
[    3s] Source dir: /home/abuild/rpmbuild/BUILD/parlatype-1.6.1
[    3s] Build dir: /home/abuild/rpmbuild/BUILD/parlatype-1.6.1/build
[    3s] Build type: native build
[    3s] Project name: parlatype
[    3s] Project version: 1.6.1
[    3s] Appending CFLAGS from environment: '-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    3s] C compiler for the build machine: cc (gcc 9.1.1 "cc (SUSE Linux) 9.1.1 20190611 [gcc-9-branch revision 272147]")
[    3s] Appending CFLAGS from environment: '-O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g'
[    3s] C compiler for the host machine: cc (gcc 9.1.1 "cc (SUSE Linux) 9.1.1 20190611 [gcc-9-branch revision 272147]")
[    3s] Build machine cpu family: x86_64
[    3s] Build machine cpu: x86_64
[    3s] Configuring config.h using configuration
[    3s] Found pkg-config: /usr/bin/pkg-config (0.29.2)
[    3s] Run-time dependency gtk+-3.0 found: YES 3.24.10
[    3s] Run-time dependency gmodule-2.0 found: YES 2.60.5
[    3s] Run-time dependency atspi-2 found: YES 2.32.1
[    3s] Run-time dependency glib-2.0 found: YES 2.60.5
[    3s] Run-time dependency gstreamer-1.0 found: YES 1.16.0
[    3s] Run-time dependency gstreamer-audio-1.0 found: YES 1.16.0
[    3s] Library m found: YES
[    3s] Found pkg-config: /usr/bin/pkg-config (0.29.2)
[    3s] Program desktop-file-validate found: NO
[    3s] Program appstream-util found: NO
[    3s] Configuring com.github.gkarsay.parlatype.service using configuration
[    3s] Program meson_post_install.py found: YES (/usr/bin/python3 /home/abuild/rpmbuild/BUILD/parlatype-1.6.1/data/meson_post_install.py)
[    3s] Build targets in project: 24
[    3s] Found ninja-1.9.0 at /usr/bin/ninja
[    3s] + export LANG=C.UTF-8
[    3s] + LANG=C.UTF-8
[    3s] + /usr/bin/ninja -v -j8 -C build
[    3s] ninja: Entering directory `build'
[    3s] [1/48] glib-compile-resources ../libparlatype/src/resources/libparlatype.gresource.xml --sourcedir ../libparlatype/src/resources --sourcedir ../libparlatype/src --c-name _pt --internal --generate --target libparlatype/src/pt-lib-resources.c --dependency-file libparlatype/src/pt-lib-resources.c.d
[    3s] [2/48] glib-compile-resources ../libparlatype/src/resources/libparlatype.gresource.xml --sourcedir ../libparlatype/src/resources --sourcedir ../libparlatype/src --c-name _pt --internal --generate --target libparlatype/src/pt-lib-resources.h
[    3s] [3/48] /usr/bin/glib-genmarshal --prefix _pt_cclosure_marshal --valist-marshallers --output libparlatype/src/pt-marshalers.h --pragma-once --header ../libparlatype/src/ptmarshalers.list
[    3s] INFO: Reading ../libparlatype/src/ptmarshalers.list...
[    3s] [4/48] /usr/bin/glib-genmarshal --prefix _pt_cclosure_marshal --valist-marshallers --output libparlatype/src/pt-marshalers.c --body ../libparlatype/src/ptmarshalers.list --include-header pt-marshalers.h
[    3s] INFO: Reading ../libparlatype/src/ptmarshalers.list...
[    3s] [5/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-i18n.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-i18n.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-i18n.c.o' -c ../libparlatype/src/pt-i18n.c
[    3s] [6/48] cc -Ilibparlatype/tests/c65f526@@waveloader@exe -Ilibparlatype/tests -I../libparlatype/tests -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'libparlatype/tests/c65f526@@waveloader@exe/waveloader.c.o' -MF 'libparlatype/tests/c65f526@@waveloader@exe/waveloader.c.o.d' -o 'libparlatype/tests/c65f526@@waveloader@exe/waveloader.c.o' -c ../libparlatype/tests/waveloader.c
[    3s] [7/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-lib-resources.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-lib-resources.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-lib-resources.c.o' -c libparlatype/src/pt-lib-resources.c
[    3s] [8/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-marshalers.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-marshalers.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-marshalers.c.o' -c libparlatype/src/pt-marshalers.c
[    3s] [9/48] /usr/bin/meson --internal msgfmthelper ../data/com.github.gkarsay.parlatype.desktop.in data/com.github.gkarsay.parlatype.desktop desktop ../data/../po
[    3s] [10/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-wavedata.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-wavedata.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-wavedata.c.o' -c ../libparlatype/src/pt-wavedata.c
[    3s] [11/48] cc -Ilibparlatype/tests/c65f526@@wavedata@exe -Ilibparlatype/tests -I../libparlatype/tests -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'libparlatype/tests/c65f526@@wavedata@exe/wavedata.c.o' -MF 'libparlatype/tests/c65f526@@wavedata@exe/wavedata.c.o.d' -o 'libparlatype/tests/c65f526@@wavedata@exe/wavedata.c.o' -c ../libparlatype/tests/wavedata.c
[    3s] [12/48] cc -Ilibparlatype/tests/c65f526@@waveviewer@exe -Ilibparlatype/tests -I../libparlatype/tests -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'libparlatype/tests/c65f526@@waveviewer@exe/waveviewer.c.o' -MF 'libparlatype/tests/c65f526@@waveviewer@exe/waveviewer.c.o.d' -o 'libparlatype/tests/c65f526@@waveviewer@exe/waveviewer.c.o' -c ../libparlatype/tests/waveviewer.c
[    3s] [13/48] cc -Ilibparlatype/tests/c65f526@@progressdialog@exe -Ilibparlatype/tests -I../libparlatype/tests -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'libparlatype/tests/c65f526@@progressdialog@exe/progressdialog.c.o' -MF 'libparlatype/tests/c65f526@@progressdialog@exe/progressdialog.c.o.d' -o 'libparlatype/tests/c65f526@@progressdialog@exe/progressdialog.c.o' -c ../libparlatype/tests/progressdialog.c
[    3s] [14/48] cc -Ilibparlatype/tests/c65f526@@player@exe -Ilibparlatype/tests -I../libparlatype/tests -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'libparlatype/tests/c65f526@@player@exe/player.c.o' -MF 'libparlatype/tests/c65f526@@player@exe/player.c.o.d' -o 'libparlatype/tests/c65f526@@player@exe/player.c.o' -c ../libparlatype/tests/player.c
[    4s] [15/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveloader.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveloader.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveloader.c.o' -c ../libparlatype/src/pt-waveloader.c
[    4s] [16/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-progress-dialog.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-progress-dialog.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-progress-dialog.c.o' -c ../libparlatype/src/pt-progress-dialog.c
[    4s] [17/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer.c.o' -c ../libparlatype/src/pt-waveviewer.c
[    4s] [18/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-cursor.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-cursor.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-cursor.c.o' -c ../libparlatype/src/pt-waveviewer-cursor.c
[    4s] [19/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-focus.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-focus.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-focus.c.o' -c ../libparlatype/src/pt-waveviewer-focus.c
[    4s] [20/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-ruler.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-ruler.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-ruler.c.o' -c ../libparlatype/src/pt-waveviewer-ruler.c
[    4s] [21/48] glib-compile-resources ../src/resources/parlatype.gresource.xml --sourcedir ../src/resources --sourcedir ../src --c-name _pt --internal --generate --target src/pt-win-resources.h
[    4s] [22/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-player.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-player.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-player.c.o' -c ../libparlatype/src/pt-player.c
[    4s] [23/48] glib-compile-resources ../src/resources/parlatype.gresource.xml --sourcedir ../src/resources --sourcedir ../src --c-name _pt --internal --generate --target src/pt-win-resources.c --dependency-file src/pt-win-resources.c.d
[    4s] [24/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-selection.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-selection.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-selection.c.o' -c ../libparlatype/src/pt-waveviewer-selection.c
[    4s] [25/48] /usr/bin/meson --internal msgfmthelper ../data/com.github.gkarsay.parlatype.appdata.xml.in data/com.github.gkarsay.parlatype.appdata.xml xml ../data/../po
[    4s] [26/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o' -c ../libparlatype/src/pt-waveviewer-waveform.c
[    4s] [27/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/meson-generated_.._pt-win-resources.c.o' -MF 'src/25a6634@@parlatype@exe/meson-generated_.._pt-win-resources.c.o.d' -o 'src/25a6634@@parlatype@exe/meson-generated_.._pt-win-resources.c.o' -c src/pt-win-resources.c
[    4s] [28/48] /usr/bin/meson --internal msgfmthelper ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml xml ../libreoffice/../po
[    4s] FAILED: libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml 
[    4s] /usr/bin/meson --internal msgfmthelper ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml xml ../libreoffice/../po
[    4s] msgfmt: cannot locate ITS rules for ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in
[    4s] [29/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/main.c.o' -MF 'src/25a6634@@parlatype@exe/main.c.o.d' -o 'src/25a6634@@parlatype@exe/main.c.o' -c ../src/main.c
[    4s] [30/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/pt-app.c.o' -MF 'src/25a6634@@parlatype@exe/pt-app.c.o.d' -o 'src/25a6634@@parlatype@exe/pt-app.c.o' -c ../src/pt-app.c
[    4s] [31/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/pt-asr-output.c.o' -MF 'src/25a6634@@parlatype@exe/pt-asr-output.c.o.d' -o 'src/25a6634@@parlatype@exe/pt-asr-output.c.o' -c ../src/pt-asr-output.c
[    4s] [32/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/pt-asr-assistant-helpers.c.o' -MF 'src/25a6634@@parlatype@exe/pt-asr-assistant-helpers.c.o.d' -o 'src/25a6634@@parlatype@exe/pt-asr-assistant-helpers.c.o' -c ../src/pt-asr-assistant-helpers.c
[    4s] [33/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/pt-asr-assistant.c.o' -MF 'src/25a6634@@parlatype@exe/pt-asr-assistant.c.o.d' -o 'src/25a6634@@parlatype@exe/pt-asr-assistant.c.o' -c ../src/pt-asr-assistant.c
[    4s] [34/48] cc -Isrc/25a6634@@parlatype@exe -Isrc -I../src -I. -I../ -Ilibparlatype/src -I../libparlatype/src -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/libxkbcommon -I/usr/include/wayland -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/freetype2 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -fdiagnostics-color=always -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -pthread -MD -MQ 'src/25a6634@@parlatype@exe/pt-mediakeys.c.o' -MF 'src/25a6634@@parlatype@exe/pt-mediakeys.c.o.d' -o 'src/25a6634@@parlatype@exe/pt-mediakeys.c.o' -c ../src/pt-mediakeys.c
[    5s] [35/48] cc  -o libparlatype/src/libparlatype.so.2.1.0 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-lib-resources.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/meson-generated_.._pt-marshalers.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-i18n.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-player.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-progress-dialog.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-wavedata.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveloader.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-cursor.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-focus.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-ruler.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-selection.c.o' 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o' -Wl,--no-undefined -Wl,--as-needed -shared -fPIC -Wl,--start-group -Wl,-soname,libparlatype.so.2 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -flto=8 -g -Wl,--version-script,/home/abuild/rpmbuild/BUILD/parlatype-1.6.1/libparlatype/src/libparlatype.map /usr/lib64/libgtk-3.so /usr/lib64/libgdk-3.so /usr/lib64/libpangocairo-1.0.so /usr/lib64/libpango-1.0.so /usr/lib64/libatk-1.0.so /usr/lib64/libcairo-gobject.so /usr/lib64/libcairo.so /usr/lib64/libgdk_pixbuf-2.0.so /usr/lib64/libgio-2.0.so /usr/lib64/libgobject-2.0.so /usr/lib64/libglib-2.0.so -Wl,--export-dynamic -pthread /usr/lib64/libgmodule-2.0.so /usr/lib64/libgstreamer-1.0.so /usr/lib64/libgstaudio-1.0.so /usr/lib64/libgstbase-1.0.so -lm -Wl,--end-group
[    5s] ninja: build stopped: subcommand failed.
[    5s] error: Bad exit status from /var/tmp/rpm-tmp.GOOBWZ (%build)
```

I dont see the mistake right now. Do you?

**Comment by gkarsay** [comment]
> [    4s] msgfmt: cannot locate ITS rules for ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in

The ITS rules for metainfo.xml files are well hidden in the `appstream` package, at least on Debian. It has `/usr/share/gettext/its/metainfo.its`.

**Comment by gkarsay** [comment]
Did you have some success with this? In the meantime I have released version 1.6.2. I would suggest to skip 1.6.1. If you need any help just ask.

**Comment by jubalh** [comment]
Thanks for following up on this. And sorry for not replying here earlier.

I still get:
```[   18s] [24/48] cc -Ilibparlatype/src/1c6e8de@@parlatype@sha -Ilibparlatype/src -I../libparlatype/src -I. -I../ -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/uuid -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libdrm -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/wayland -I/usr/include/libxkbcommon -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -I/usr/include/gstreamer-1.0 -I/usr/include/orc-0.4 -fdiagnostics-color=al
ways -pipe -D_FILE_OFFSET_BITS=64 '-DLOCALEDIR="/usr/share/locale"' -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=8 -g -fPIC -pthread -MD -MQ 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o' -MF 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o.d' -o 'libparlatype/src/1c6e8de@@parlatype@sha/pt-waveviewer-waveform.c.o' -c ../libparlatype/src/pt-waveviewer-waveform.c                                                           
[   18s] [25/48] /usr/bin/meson --internal msgfmthelper ../data/com.github.gkarsay.parlatype.desktop.in data/com.github.gkarsay.parlatype.desktop desktop ../data/../po                      
[   18s] [26/48] /usr/bin/meson --internal msgfmthelper ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml xml ../libreoffice/../po                                                                                                                                                 
[   18s] FAILED: libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml                                                                                                   
[   18s] /usr/bin/meson --internal msgfmthelper ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml xml ../libreoffice/../po                                                                                                                                                         
[   18s] msgfmt: cannot locate ITS rules for ../libreoffice/com.github.gkarsay.parlatype.libreoffice_helpers.metainfo.xml.in    
```

And actually I'm not sure what I should do/change.

**Comment by gkarsay** [comment]
The ITS rules seem to be in package AppStream-devel in Tumbleweed.

**Comment by jubalh** [comment]
Adding `AppStream-devel` solved this.

Would you mind explaining to me what actually is happening? What are the ITS files, what does AppStream-devel provide and how does parlatype make use of it?

**Comment by gkarsay** [comment]
This is for gettext to translate metainfo.xml files. Quoting gettext:

> Marking translatable strings in an XML file is done through a separate "rule" file, making use of the Internationalization Tag Set standard (ITS, https://www.w3.org/TR/its20/).

For each type of XML files gettext needs a rule file. For metainfo.xml it is `/usr/share/gettext/its/metainfo.its`. In Tumbleweed this is in the AppStream-devel package, while in Debian it is in the appstream package. You need it only once at build time.
